import 'expo-router/entry';
// DO NOT TOUCH THIS
// NEVER HAVE I EVER HAD TO USE THIS FILE BUT IF YOU REMOVE THIS THE APP WILL CRASH.
// I HAVE TRIED CHANGING THE ENTRYPOINT IN PACKAGE-LOCK.JSON BUT IT REFUSES TO WORK